apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-dev
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/podinfo/dev
  prune: true
  interval: 2m
  targetNamespace: dev-podinfo
  timeout: 3m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: dev-podinfo
      namespace: dev-podinfo