apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo-production
namePrefix: prod-
namespace: prod-podinfo
resources:
  - namespace.yaml
  - ../base
patches:
  - target:
      kind: Deployment
      name: podinfo
    patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: podinfo
        spec:
          replicas: 3