apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo-dev
resources:
  - namespace.yaml
  - ../base
namePrefix: dev-
namespace: dev-podinfo
patches:
    - target:
        kind: Deployment
        name: podinfo
      patch: |-
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: podinfo
          spec:
            replicas: 1
            template:
              spec:
                containers:
                  - name: podinfo
                    env:
                      - name: PODINFO_UI_COLOR
                        value: "#green"
                      - name: PODINFO_UI_MESSAGE
                        value: "Development Environment"