apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-dev
  namespace: flux-system
spec:
  targetNamespace: dev-podinfo
  interval: 5m
  path: ./apps/podinfo/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system