apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo-production
  namespace: flux-system
resources:
  - namespace.yaml
  - ../base

patches:
  - target:
      kind: Deployment
      name: podinfo
    patch: |-
      - op: replace
        path: ../base/deployment.yaml
        value: |-
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: podinfo
          spec:
            replicas: 3